# Site
name: "Daesung's Tower"
description: '천천히 쌓아봅쉬다..'
logo: 'assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: ''
disqus: 'daesungkim'
email: 'treeboy2762@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-katex

  
authors:
    daesungkim:
      name:           Daesung Kim
      site:           https://www.daesungkim.com
      avatar:         assets/images/uploads/profile.png
      bio:            "Demystifying computer vision"
      email:          daesungkim@yonsei.ac.kr
      twitter:        https://velog.io/@treeboy2762
      github:         Treeboy2762
      instagram:      daxingdaxing
      linkedin:       daesung-kim-1a14421b2


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: daesungkim
      avatar: assets/images/uploads/profile.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  syntax_highlighter: rouge


# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]